---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: docker://lpenz/omnilint:0.5.2
  python:
    uses: lpenz/ghworkflow-python/.github/workflows/python.yml@v0.8.1
    with:
      coveralls: true
      docs: true
      publish_pypi: true
      publish_github_release: true
      publish_packagecloud: false
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build
      - run: nix flake check
  publish-cachix:
    needs: [ omnilint, python, nix ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.14.0
      - uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          skipPush: ${{ steps.version.outputs.version_commit == '' }}
          name: lpenz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
      - run: nix flake check
